### ISSUE TITLE
Upių valstybinio monitoringo duomenys

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/manifest#1009]
**Organizacija**: Aplinkos apsaugos agentūra
**Alternatyvūs duomenų rinkinio pavadinimai**:
- 2.6. Upių valstybinio monitoringo duomenys

**data.gov.lt**: [Upių valstybinio monitoringo duomenys](https://data.gov.lt/dataset/upiu-bukle)

**Comment by dovele** [comment]
Nauja data.gov.lt nuoroda: [Upių valstybinio monitoringo duomenys](https://data.gov.lt/dataset/upiu-valstybinio-monitoringo-duomenys)
