### ISSUE TITLE
Sveikatos priežiūros įstaigų licencijų duomenys (duomenys apie sveikatos priežiūros įstaigų  licencijas, veiklos adresus ir teikiamas sveikatos priežiūros paslaugas)

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/manifest#1147]
**Organizacija**: Valstybinė akreditavimo sveikatos priežiūros veiklai tarnyba prie Sveikatos apsaugos ministerijos
**Planuojamų duomenų atvėrimo veilų pradžia ir pabaiga**: 2021-10 - 2022-03
**Alternatyvūs duomenų rinkinio pavadinimai**:
- 25.1. Sveikatos priežiūros įstaigų licencijų duomenys (duomenys apie sveikatos priežiūros įstaigų  licencijas, veiklos adresus ir teikiamas sveikatos priežiūros paslaugas)

**data.gov.lt**: [Sveikatos priežiūros įstaigų licencijų duomenys](https://data.gov.lt/dataset/sveikatos-prieziuros-istaigu-licenciju-duomenys)

**Comment by DaumantasJauga** [comment]
Sveikas, kada bus įkelta į duomenų saugyklą?

**Comment by sirex** [comment]
> @sirex kada bus įkelta į duomenų saugyklą?

Atsiprašau, vėluoju. Jau atnaujinta.
