### ISSUE TITLE
Lietuvos geologijos tarnyba, žemės ištekliai

### ISSUE THREAD

**Issue by Marius-prog** [atviriduomenys/manifest#1577]
žemės gelmių išteklių rūšių klasifikatorius

**Comment by IngaIVPK** [comment]
Organizacija: Lietuvos geologijos tarnyba
Planuojamų duomenų atvėrimo veiklų pradžia ir pabaiga: 2022-03 - 2022-06

data.gov.lt: [Žemės gelmių išteklių rūšys (klasifikatorius)](https://data.gov.lt/dataset/zemes-gelmiu-istekliu-rusys-klasifikatorius)
