### ISSUE TITLE
Lietuvos geologijos tarnyba, geologiniai tyrimai

### ISSUE THREAD

**Issue by Marius-prog** [atviriduomenys/manifest#1579]
geologinių tyrimų rinkinys

**Comment by IngaIVPK** [comment]
Organizacija: Lietuvos geologijos tarnyba
Planuojamų duomenų atvėrimo veiklų pradžia ir pabaiga: 2022-03 - 2022-06

data.gov.lt: [Geologinių tyrimų ataskaitų katalogas](https://data.gov.lt/dataset/geologiniu-tyrimu-ataskaitu-katalogas)
