### ISSUE TITLE
Lietuvos geologijos tarnyba, geotopai

### ISSUE THREAD

**Issue by Marius-prog** [atviriduomenys/manifest#1581]

**Comment by IngaIVPK** [comment]
Organizacija: Lietuvos geologijos tarnyba
Planuojamų duomenų atvėrimo veiklų pradžia ir pabaiga: 2022-03 - 2022-06

data.gov.lt: [Geotopų sąrašas (katalogas)](https://data.gov.lt/dataset/geotopu-sarasas-katalogas)
