### ISSUE TITLE
Geologijos tarnyba, leidimai naudoti iškasenas

### ISSUE THREAD

**Issue by Marius-prog** [atviriduomenys/manifest#1599]

**Comment by IngaIVPK** [comment]
Organizacija: Lietuvos geologijos tarnyba
Planuojamų duomenų atvėrimo veiklų pradžia ir pabaiga: 2022-03 - 2022-06

data.gov.lt: [Leidimų naudoti naudingųjų iškasenų (išskyrus angliavandenilius), požeminio vandens išteklius ir žemės gelmių ertmes, duomenys](https://data.gov.lt/dataset/leidimu-naudoti-naudinguju-iskasenu-isskyrus-angliavandenilius-pozeminio-vandens-isteklius-ir-zemes-gelmiu-ertmes-duomenys)
