### ISSUE TITLE
Geologijos tarnyba, naudingųjų iškasenų gavyba

### ISSUE THREAD

**Issue by Marius-prog** [atviriduomenys/manifest#1606]

**Comment by IngaIVPK** [comment]
Organizacija: Lietuvos geologijos tarnyba
Planuojamų duomenų atvėrimo veiklų pradžia ir pabaiga: 2022-03 - 2022-06

data.gov.lt: [Apibendrinti naudingųjų iškasenų ir požeminio vandens gavybos duomenys](https://data.gov.lt/dataset/apibendrinti-naudinguju-iskasenu-ir-pozeminio-vandens-gavybos-duomenys)
