### ISSUE TITLE
Geologija, požeminio vandens lygių monitoringo duomenys

### ISSUE THREAD

**Issue by Marius-prog** [atviriduomenys/manifest#1610]

**Comment by IngaIVPK** [comment]
Organizacija: Lietuvos geologijos tarnyba
Planuojamų duomenų atvėrimo veiklų pradžia ir pabaiga: 2022-03 - 2022-06

data.gov.lt: [Valstybinio požeminio vandens monitoringo lygio matavimų duomenys](https://data.gov.lt/dataset/valstybinio-pozeminio-vandens-monitoringo-pozeminio-vandens-lygio-duomenys)
