### ISSUE TITLE
Ūkio subjektų aplinkos oro taršos šaltinių ir iš jų išmetamų teršalų inventorizacijos duomenys

### ISSUE THREAD

**Issue by sirex** [atviriduomenys/manifest#304]
**Organizacija**: Aplinkos apsaugos agentūra
**Alternatyvūs duomenų rinkinio pavadinimai**:
- 2.13. Ūkio subjektų aplinkos oro taršos šaltinių ir iš jų išmetamų teršalų inventorizacijos duomenys
- Ūkio subjektų aplinkos oro taršos šaltinių ir iš jų išmetamų teršalų inventorizacijos duomenys.

**data.gov.lt**: [Ūkio subjektų aplinkos oro taršos šaltinių ir iš jų išmetamų teršalų inventorizacijos duomenys.](https://data.gov.lt/dataset/ukio-subjektu-aplinkos-oro-tarsos-saltiniu-ir-is-ju-ismetamu-tersalu-inventorizacijos-duomenys)

**Comment by dovele** [comment]
Atnaujintas pavadinimas: Ūkio subjektų aplinkos oro taršos šaltinių ir iš jų išmetamų teršalų inventorizacijų sąrašas
