### ISSUE TITLE
Kauno miesto savivaldybės sistema KASIMAI

### ISSUE THREAD

**Issue by hishonor13** [atviriduomenys/manifest#3384]

**Comment by JustinasKen** [comment]
Modelio pavadinimai privalo prasidėti didžiąja raide.

Bandant praleisti pro naują `spinta` versijos `check` komandą gaunam klaidą.

**Comment by hishonor13** [comment]
> Modelio pavadinimai privalo prasidėti didžiąja raide.
> 
> Bandant praleisti pro naują `spinta` versijos `check` komandą gaunam klaidą.

Pataisyta
