### ISSUE TITLE
Statistics

### ISSUE THREAD

**Issue by aidiss** [atviriduomenys/manifest#5]
Do we have any tools that calculate some stats about this repo?

**Comment by sirex** [comment]
Yes, we definitely need. My plan is to create a dashboard on atviriduomenys.lt and show the stats, progress and etc. But before doing that, I would like to describe more data, to see if data model works. Once I will be satisfied with the data model, then I want to announce that and see if there is any interest.

**Comment by sirex** [comment]
Currently you can see the statistics here: https://nbviewer.jupyter.org/github/atviriduomenys/manifest/blob/master/notebooks/metrics.ipynb
