### ISSUE TITLE
Tools that use the information we gather here.

### ISSUE THREAD

**Issue by aidiss** [atviriduomenys/manifest#6]
Are there any tools that can leverage the info we give about sources?
Is databot related to this?

**Comment by sirex** [comment]
databot is not related to this and currently there are no tools, except one validation script https://github.com/sirex/opendata/blob/master/scripts/check.py

But I'm trying to come up with a data model, where all those yaml files could be easily converted to other formats, like DCAT, DataPackage and etc. Then we will have plenty of tools.

Also I have plans to propose this data model for the government, so maybe they will use it, for extracting and transforming data.

In addition to this validation script, I want to create other scripts to convert to DCAT and DataPackage, maybe a script, that could populate data to CKAN. And of course I want to create a dashboard with the stats and progress.

**Comment by sirex** [comment]
Currently https://github.com/atviriduomenys/spinta is the main tool, that uses manifest data.
