### ISSUE TITLE
Duomenys apie Lietuvos pareiškėjų finansuotas paraiškas ES mokslinių tyrimų ir inovacijų programose "Horizon 2020", "Horizon Europe"

### ISSUE THREAD

**Issue by DaumantasJauga** [atviriduomenys/manifest#951]
Valdytojas: Mokslo, inovacijų ir technologijų agentūra

Valdytojo sritis: Ūkio ministerija

Tvarkytojas: Mokslo, inovacijų ir technologijų agentūra

IS/Registras: Mokslinių tyrimų ir eksperimentinės plėtros informacinė sistema

Ar reikia nuasmeninti: Ne

Ar duomenų rinkinys yra atvertas: Ne

**Comment by sirex** [comment]
https://data.gov.lt/dataset/duomenys-apie-lietuvos-pareiskeju-finansuotas-paraiskas-es-moksliniu-tyrimu-ir-inovaciju-programose
